# Chon: random_forest, gradient_boosting, logistic_regression
model_type: random_forest

# Sieu tham so cho mo hinh RandomForestClassifier dang duoc deploy
n_estimators: 300
max_depth: null
min_samples_split: 2
